# Surge iOS 专用 us-n-home 策略组
# 本文件用于远程 #!include
# 用户本地必须自行定义 US[N-Home]（AnyTLS 主用节点）

[Proxy Group]

USNHome = select, USN[北美洲], USN[大洋洲], USN[欧洲], USN[亚洲]

USN[北美洲] = select, policy-path=https://raw.githubusercontent.com/csjcsl666/surge-usnhome/main/usnhome.list, policy-regex-filter=-(US|CA)\], underlying-proxy=US[N-Home], update-interval=86400, no-alert=0, hidden=1, include-all-proxies=0

USN[大洋洲] = select, policy-path=https://raw.githubusercontent.com/csjcsl666/surge-usnhome/main/usnhome.list, policy-regex-filter=-(AU)\], underlying-proxy=US[N-Home], update-interval=86400, no-alert=0, hidden=1, include-all-proxies=0

USN[欧洲] = select, policy-path=https://raw.githubusercontent.com/csjcsl666/surge-usnhome/main/usnhome.list, policy-regex-filter=-(FR|UK|DE|TR)\], underlying-proxy=US[N-Home], update-interval=86400, no-alert=0, hidden=1, include-all-proxies=0

USN[亚洲] = select, policy-path=https://raw.githubusercontent.com/csjcsl666/surge-usnhome/main/usnhome.list, policy-regex-filter=-(SG|JP|PH)\], underlying-proxy=US[N-Home], update-interval=86400, no-alert=0, hidden=1, include-all-proxies=0
