# Surge iOS 专用 us-n-home 策略组
# 本文件用于远程 #!include
# 用户本地必须自行定义 US[N-Home]（AnyTLS 主用节点）

[Proxy Group]

USNHome = select, policy-path=https://raw.githubusercontent.com/csjcsl666/surge-usnhome/main/usnhome.list, update-interval=86400, underlying-proxy=US[N-Home]
